# Generated by Django 4.1.7 on 2023-03-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pokemon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemons",
            name="Attack",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pokemons",
            name="Defense",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pokemons",
            name="Generation",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pokemons",
            name="Hp",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pokemons",
            name="SpAtk",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pokemons",
            name="SpDef",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pokemons",
            name="Speed",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pokemons",
            name="Total",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
