# Generated by Django 4.1.7 on 2023-03-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pokemon", "0004_rename_pokemons_pokemon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="Id",
            field=models.CharField(
                max_length=3, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="Name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="Type1",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="Type2",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
