# Generated by Django 4.1.7 on 2023-03-26 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Pokemon", "0005_alter_pokemon_id_alter_pokemon_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemon", old_name="Attack", new_name="attack",
        ),
        migrations.RenameField(
            model_name="pokemon", old_name="Defense", new_name="defense",
        ),
        migrations.RenameField(
            model_name="pokemon", old_name="Generation", new_name="generation",
        ),
        migrations.RenameField(model_name="pokemon", old_name="Hp", new_name="hp",),
        migrations.RenameField(model_name="pokemon", old_name="Id", new_name="id",),
        migrations.RenameField(
            model_name="pokemon", old_name="Legendary", new_name="legendary",
        ),
        migrations.RenameField(model_name="pokemon", old_name="Name", new_name="name",),
        migrations.RenameField(
            model_name="pokemon", old_name="SpAtk", new_name="spatk",
        ),
        migrations.RenameField(
            model_name="pokemon", old_name="SpDef", new_name="spdef",
        ),
        migrations.RenameField(
            model_name="pokemon", old_name="Speed", new_name="speed",
        ),
        migrations.RenameField(
            model_name="pokemon", old_name="Total", new_name="total",
        ),
        migrations.RenameField(
            model_name="pokemon", old_name="Type1", new_name="type1",
        ),
        migrations.RenameField(
            model_name="pokemon", old_name="Type2", new_name="type2",
        ),
    ]
