# Generated by Django 4.1.7 on 2023-03-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pokemon", "0006_rename_attack_pokemon_attack_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemon", old_name="spatk", new_name="sp_atk",
        ),
        migrations.RenameField(
            model_name="pokemon", old_name="spdef", new_name="sp_def",
        ),
        migrations.AddField(
            model_name="pokemon",
            name="image_url",
            field=models.URLField(
                default=models.CharField(
                    max_length=3, primary_key=True, serialize=False, unique=True
                )
            ),
        ),
    ]
