# Generated by Django 4.1.7 on 2023-03-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pokemon", "0007_rename_spatk_pokemon_sp_atk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon", name="image_url", field=models.URLField(),
        ),
    ]
