# Generated by Django 4.1.7 on 2023-03-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pokemon", "0008_alter_pokemon_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
